@DotNetAPI_HostAddress = https://localhost:5001

GET {{DotNetAPI_HostAddress}}/pizza/
Accept: application/json

###

GET {{DotNetAPI_HostAddress}}/pizza/1
Accept: application/json

###

GET {{DotNetAPI_HostAddress}}/pizza/5
Accept: application/json

###

POST {{DotNetAPI_HostAddress}}/pizza/
Content-Type: application/json

{
  "name": "Hawaii",
  "isGlutenFree": false
}

###

PUT {{DotNetAPI_HostAddress}}/pizza/3
Content-Type: application/json

{
    "id": 3,
    "name": "Hawaiian",
    "isGlutenFree": false
}

###

DELETE {{DotNetapi_HostAddress}}/pizza/4

###